import type { ResultsData } from "@/types/session";

export function generateSessionMarkdown(data: ResultsData): string {
  const date = new Date(data.completedAt).toLocaleDateString();
  
  let md = `# DevPrep Session Results: ${data.category.replace(/_/g, " ").toUpperCase()}\n\n`;
  md += `**Date:** ${date}\n`;
  md += `**Difficulty:** ${data.difficulty}\n`;
  md += `**Overall Score:** ${Math.round(data.overallScore)}/100\n`;
  md += `**Duration:** ${Math.floor((data.duration || 0) / 60)}m ${(data.duration || 0) % 60}s\n\n`;

  md += `## Overall Criteria Breakdown\n\n`;
  Object.entries(data.criteriaAverages).forEach(([key, value]) => {
    md += `- **${key.replace(/_/g, " ").toUpperCase()}:** ${value}%\n`;
  });
  md += `\n---\n\n`;

  data.questions.forEach((q) => {
    md += `### Question ${q.questionIndex}\n\n`;
    md += `**Question:** ${q.questionText}\n\n`;
    md += `**Your Answer:**\n> ${q.candidateAnswer}\n\n`;
    
    if (q.candidateCode) {
      md += "```\n" + q.candidateCode + "\n```\n\n";
    }

    md += `**Score:** ${q.score}/100\n\n`;
    
    if (q.criteria) {
      md += `**Criteria Details:**\n`;
      Object.entries(q.criteria).forEach(([k, v]) => {
        md += `- ${k.replace(/_/g, " ")}: ${v}%\n`;
      });
      md += "\n";
    }

    md += `**AI Feedback:**\n${q.feedback}\n\n`;
    
    if (q.modelAnswer) {
      md += `**Model Answer:**\n${q.modelAnswer}\n\n`;
    }

    md += `---\n\n`;
  });

  md += `*Generated by DevPrep - Your AI Coding Interview Partner*`;

  return md;
}

export function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
